COMMON:
  save_model_dir : saved_models
  model_name : laa
  log_dir : logs
  device : cuda:0
  exp_dir : experiments

DATA:
  data_dir :  datasets/silver_corpus
  train_data_file :  Data_train.h5
  train_label_file :  Label_train.h5
  train_class_weights_file :  Class_Weight_train.h5
  train_weights_file :  Weight_train.h5
  test_data_file :  Data_test.h5
  test_label_file :  Label_test.h5
  test_class_weights_file :  Class_Weight_test.h5
  test_weights_file :  Weight_test.h5
  labels : [ Background ,  Left WM ,  Left Cortex ,  Left Lateral ventricle ,
             Left Inf LatVentricle ,  Left Cerebellum WM ,  Left Cerebellum Cortex ,
             Left Thalamus ,  Left Caudate ,  Left Putamen ,  Left Pallidum ,  3rd Ventricle ,
             4th Ventricle ,  Brain Stem ,  Left Hippocampus ,  Left Amygdala ,  CSF (Cranial) ,
             Left Accumbens ,  Left Ventral DC ,  Right WM ,  Right Cortex ,  Right Lateral Ventricle ,
             Right Inf LatVentricle ,  Right Cerebellum WM ,  Right Cerebellum Cortex ,  Right Thalamus ,
             Right Caudate ,  Right Putamen ,  Right Pallidum ,  Right Hippocampus ,  Right Amygdala ,
             Right Accumbens ,  Right Ventral DC ]

NETWORK:
  num_class : 2
  num_channels : 1
  num_filters : 64
  kernel_h : 5
  kernel_w : 5
  kernel_c : 1
  stride_conv : 1
  pool : 2
  stride_pool : 2
  se_block :  SSE  #Valid options : NONE, CSE, SSE, CSSE
  drop_out : 0

TRAINING:
  fold : fold2
  exp_name :  laa
  final_model_file :  laa.pth.tar
  learning_rate : 0.001
  momentum : 0.95
  optim_weight_decay : 0.00001
  train_batch_size : 2
  val_batch_size : 2
  log_nth : 10
  num_epochs : 200
  optim_betas : (0.9, 0.999)
  optim_eps : 0.00000001
  lr_scheduler_step_size : 10
  lr_scheduler_gamma : 0.5
  iterations: 1000
  test_iterations: 1000
  pre_trained_path :

  #Uses the last checkpoint file from the exp_dir_name folder
  use_last_checkpoint : True

EVAL:
  eval_model_path :  few_shot_segmentation
  data_dir :  /home/deeplearning/Abhijit/nas_drive/Abhijit/WholeBody/CT_ce/Data/Visceral
  label_dir :  /home/deeplearning/Abhijit/nas_drive/Abhijit/WholeBody/CT_ce/Data/Visceral
  volumes_txt_file :  datasets/MALC/test_volumes.txt
  query_txt_file :  datasets/eval_query.txt
  support_txt_file :  datasets/eval_support.txt
  remap_config :  WholeBody  #Valid options : Neo, FS, WholeBody
  orientation :  AXI  #Valid options : COR, AXI, SAG
  save_predictions_dir :  copy_over
